# Generated by Django 4.1.4 on 2023-03-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=140, unique=True)),
                ('solved', models.BooleanField(default=False)),
            ],
        ),
    ]
