# Generated by Django 4.1.4 on 2023-02-17 14:02

from django.db import migrations


def populate_database(apps, schema_editor):
    solved_steps = [
        "tablero_herramientas",
        "licuadora",
        "soporte_especieros",
        "soporte_cuchillos",
        "soporte_pies",
        "teclado_heladera",
        "cuadro",
        "caldera"
    ]
    Step = apps.get_model("deviceController", "Step")
    count = Step.objects.count()
    if count == 0:
        for stepname in solved_steps:
            Step.objects.create(
                step_name=stepname, solved=False
            )


class Migration(migrations.Migration):

    dependencies = [
        ('deviceController', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_database),
    ]
