# Generated by Django 4.1.4 on 2023-03-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceController', '0002_auto_20230302_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=140, unique=True)),
                ('fixed_brightness', models.IntegerField()),
                ('scary_brightness', models.IntegerField()),
                ('uv_light_active', models.BooleanField()),
                ('flicker_min_time', models.IntegerField()),
                ('flicker_max_time', models.IntegerField()),
                ('blackout_min_time', models.IntegerField()),
                ('blackout_max_time', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='LightsJSON',
        ),
    ]
