# Generated by Django 4.1.4 on 2023-02-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceController', '0002_auto_20230217_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
