# Generated by Django 4.1.4 on 2023-03-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceController', '0003_lightconfig_delete_lightsjson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightconfig',
            name='mode',
            field=models.CharField(choices=[('fixed', 'Modo fijo'), ('scary', 'Modo Asustadizo'), ('panic', 'Modo Panico (luces en rojo)'), ('off', 'Luces apagadas')], max_length=140, unique=True),
        ),
    ]
