# Generated by Django 4.1.4 on 2023-02-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceController', '0004_auto_20230217_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='step_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
