# Generated by Django 4.1.4 on 2023-03-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deviceController', '0004_alter_lightconfig_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lightconfig',
            old_name='fixed_brightness',
            new_name='rgb_brightness',
        ),
        migrations.RenameField(
            model_name='lightconfig',
            old_name='scary_brightness',
            new_name='uv_brightness',
        ),
        migrations.RemoveField(
            model_name='lightconfig',
            name='uv_light_active',
        ),
    ]
