# Generated by Django 4.1.4 on 2023-02-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceController', '0005_alter_step_step_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='step_name',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
